#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "running cowtest")
def test_cowtest():
    r.run_qemu(shell_script(["cowtest"]), timeout=300)

@test(8, "cowtest: simple", parent=test_cowtest)
def test_cow_simple():
    assert_equal(len(re.findall("^simple: ok$", r.qemu.output, re.M)), 2)

@test(8, "cowtest: three", parent=test_cowtest)
def test_cow_three():
    assert_equal(len(re.findall("^three: ok$", r.qemu.output, re.M)), 3)

@test(7, "cowtest: file", parent=test_cowtest)
def test_cow_file():
    r.match("^file: ok$")

@test(7, "cowtest: forkfork", parent=test_cowtest)
def test_cow_forkfork():
    r.match("^forkfork: ok$")

@test(0, "running mmaptest")
def test_mmaptest():
    r.run_qemu(shell_script(["mmaptest"]), timeout=240)

@test(5, "mmaptest: basic", parent=test_mmaptest)
def test_mmap_basic():
    r.match("^test basic mmap: OK$")

@test(4, "mmaptest: private", parent=test_mmaptest)
def test_mmap_private():
    r.match("^test mmap private: OK$")

@test(3, "mmaptest: read-only", parent=test_mmaptest)
def test_mmap_readonly():
    r.match("^test mmap read-only: OK$")

@test(3, "mmaptest: read/write", parent=test_mmaptest)
def test_mmap_readwrite():
    r.match("^test mmap read/write: OK$")

@test(4, "mmaptest: dirty", parent=test_mmaptest)
def test_mmap_dirty():
    r.match("^test mmap dirty: OK$")

@test(2, "mmaptest: not-mapped unmap", parent=test_mmaptest)
def test_mmap_unmapped():
    r.match("^test not-mapped unmap: OK$")

@test(4, "mmaptest: lazy access", parent=test_mmaptest)
def test_mmap_lazy():
    r.match("^test lazy access: OK$")

@test(2, "mmaptest: two files", parent=test_mmaptest)
def test_mmap_two_files():
    r.match("^test mmap two files: OK$")

@test(3, "mmaptest: fork", parent=test_mmaptest)
def test_mmap_fork():
    r.match("^test fork: OK$")

@test(3, "mmaptest: munmap prevents access", parent=test_mmaptest)
def test_mmap_noaccess():
    r.match("^test munmap prevents access: OK$")

@test(2, "mmaptest: read-only protection", parent=test_mmaptest)
def test_mmap_protection():
    r.match("^test writes to read-only mapped memory: OK$")

@test(0, "running integration tests")
def test_vmtest():
    r.run_qemu(shell_script(["vmtest"]), timeout=180)

@test(8, "vmtest: private mapping across fork", parent=test_vmtest)
def test_vm_private():
    r.match("^vmtest: private fork: OK$")

@test(7, "vmtest: resident shared mapping across fork", parent=test_vmtest)
def test_vm_shared():
    r.match("^vmtest: shared resident fork: OK$")

@test(20, "usertests")
def test_usertests():
    r.run_qemu(shell_script(["usertests -q"]), timeout=1000)
    r.match("^ALL TESTS PASSED$")

run_tests()
